### ISSUE TITLE
Support Pushbullet End-to-End Encryption

### ISSUE THREAD

**Issue by stgarf** [amyreese/znc-push#173]
## Woohoo! Pushbullet now offers End-to-End Encryption. Please implement support for it -- thank you!

End-to-End Encryption

Pushbullet already encrypts your data in transit using https. Enabling end-to-end encryption adds an additional layer of privacy for your phone's notifications, clipboard, and SMS sync.

Enter a password to enable end-to-end encryption. You will need to enter this password on each of your devices.

**Comment by nibogd** [comment]
Hi! I saw the 'needs-contributor' badge and tried to implement this... When it was a half done, saw [this announcement](https://blog.pushbullet.com/2015/08/11/end-to-end-encryption/): it says that only notification mirroring, clipboard and SMS support e2e encryption.
